
2022-03-03 09:36:09.844439

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:00:03.957627

Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\pandas\\compat\\__init__.pyd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 2, in <module>
    import pandas
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import (
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1386, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1532, in find_spec
  File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
KeyboardInterrupt

2022-03-03 11:25:00.780523

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:25:07.072389

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:25:13.363523

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:27:15.099915

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:27:21.389461

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:27:27.663760

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:27:33.943222

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:27:40.225012

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:27:46.507827

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:28:24.713985

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:28:32.049621

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:28:38.338283

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:28:45.643468

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:28:51.911120

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:28:59.217568

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:05.592519

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:11.883678

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:18.144263

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:24.450365

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:30.714170

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:36.989498

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:43.279225

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:49.567396

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:29:56.872565

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:30:03.126084

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:30:10.468730

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:30:16.757986

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:30:21.021716

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:30:29.521968

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:30:36.958068

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:40:38.190894

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:40:45.497473

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:40:51.790707

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:40:59.116771

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:41:05.401755

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:41:12.715434

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:41:19.000203

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:41:26.327120

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-03 11:41:32.604014

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:15:43.169746

Traceback (most recent call lastTraceback (most recent call last):
  File "C:\Users\Admin\CODE\script\sc    print(a[1])
NameError: name 'a' is not definNameError: name 'a' is not defined

2022-03-07 10:16:39.823684

Traceback (most recent call lastTraceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:17:10.400045

Traceback (most recent call lastTrac  File "C:\Users\Admin\CODE\scri  File "C:\Users\Admin\CODE\script\sc    print(a[1])
NameError: name 'a' is not defined
Error: name 'a' is not defined

2022-03-07 10:19:10.353252

Traceback (most recent call lastTraceback (most recent call last):
  File "C:\Users\Admin\CODE\script\sc    print(a[1])
NameError: name    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:19:58.778342

Traceback (most recent call lastTraceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:20:26.077441

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined
Error: name 'a' is not defined

2022-03-07 10:20:41.587829

Traceback (most recent call lastTraceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:22:59.917060

Traceback (most recent call lastTraceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:25:56.288226

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:26:01.359735

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:26:06.415283

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:26:11.474493

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:28:35.957444

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined
Error: name 'a' is not defined

2022-03-07 10:30:46.977599

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:30:52.038475

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:30:57.086836

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:31:02.146315

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:31:07.199809

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined

2022-03-07 10:31:12.254303

Traceback (most recent call last):
  File "C:\Users\Admin\CODE\script\script1.py", line 8, in <module>
    print(a[1])
NameError: name 'a' is not defined
